name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: rustfmt, clippy

      - name: Install wasm-bindgen-cli
        run: cargo install -f wasm-bindgen-cli --version 0.2.100

      - name: Build Project for WASM
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-dir out --target web target/wasm32-unknown-unknown/release/asteroids.wasm

      - name: Copy Assets
        run: |
          cp -r assets out/
          cp index.html out/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./out
          publish_branch: web
